project_id = "ysbguilyqjecjvjzzrrz"

[functions.create-payment-intent]
verify_jwt = false

[functions.get-stripe-config]
verify_jwt = false

[functions.calculate-tax]
verify_jwt = false

[functions.manage-roles]
verify_jwt = false
